package com.musfit.integrations.healthconnect

typealias HealthConnectAuthoredRecordType = com.musfit.domain.health.HealthConnectAuthoredRecordType
typealias HealthConnectAuthoredRecord = com.musfit.domain.health.HealthConnectAuthoredRecord
typealias HealthConnectDeleteFailure = com.musfit.domain.health.HealthConnectDeleteFailure
