package com.musfit.integrations.healthconnect

typealias HealthConnectFoodExportPayload = com.musfit.domain.health.HealthConnectFoodExportPayload
typealias HealthConnectFoodMealExport = com.musfit.domain.health.HealthConnectFoodMealExport
typealias HealthConnectFoodExportResult = com.musfit.domain.health.HealthConnectFoodExportResult
