config:
  validation: true
  warningsAsErrors: true

build:
  maxIssues: 0

naming:
  FunctionNaming:
    active: false
  MatchingDeclarationName:
    active: false
  TopLevelPropertyNaming:
    active: false

style:
  MagicNumber:
    active: false
  MaxLineLength:
    active: false
